import pandas as pd

# Load the datasets
dataset1 = pd.read_csv('dataset1.csv')
dataset2 = pd.read_csv('dataset2.csv')
dataset3 = pd.read_csv('dataset3.csv')

# Print each dataset
print("Dataset 1:")
print(dataset1)
print("\nDataset 2:")
print(dataset2)
print("\nDataset 3:")
print(dataset3)

# Merge the datasets (assuming they have a common column 'id' for merging)
merged_data = pd.merge(dataset1, dataset2, on='id')
merged_data = pd.merge(merged_data, dataset3, on='id')

# Print the merged dataset
print("\nMerged Dataset:")
print(merged_data)
